/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Api */
        get: operations["metrics_api_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Defaults */
        get: operations["get_defaults_api_v1_backtest_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backtest Api */
        post: operations["run_backtest_api_api_v1_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Backtest Api */
        post: operations["start_backtest_api_api_v1_backtest_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/anchor-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest Anchor Price Api */
        post: operations["backtest_anchor_price_api_api_v1_backtest_anchor_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest Status Api */
        get: operations["backtest_status_api_api_v1_backtest__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Stream Api */
        get: operations["job_stream_api_api_v1_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest Cancel Api */
        post: operations["backtest_cancel_api_api_v1_backtest__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Params Api */
        get: operations["market_params_api_api_v1_market_params_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Optimization Api */
        post: operations["start_optimization_api_api_v1_optimization_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optimization Status Api */
        get: operations["optimization_status_api_api_v1_optimization__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{job_id}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optimization Rows Api */
        get: operations["optimization_rows_api_api_v1_optimization__job_id__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{job_id}/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optimization Heatmap Api */
        get: operations["optimization_heatmap_api_api_v1_optimization__job_id__heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{job_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optimization Progress Api */
        get: operations["optimization_progress_api_api_v1_optimization__job_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optimization History Api */
        get: operations["optimization_history_api_api_v1_optimization_history_get"];
        put?: never;
        post?: never;
        /** Optimization History Clear Api */
        delete: operations["optimization_history_clear_api_api_v1_optimization_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization-history/selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Optimization History Selected Clear Api */
        delete: operations["optimization_history_selected_clear_api_api_v1_optimization_history_selected_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization-history/restore-selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimization History Selected Restore Api */
        post: operations["optimization_history_selected_restore_api_api_v1_optimization_history_restore_selected_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimization Cancel Api */
        post: operations["optimization_cancel_api_api_v1_optimization__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{job_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimization Restart Api */
        post: operations["optimization_restart_api_api_v1_optimization__job_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{job_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optimization Export Api */
        get: operations["optimization_export_api_api_v1_optimization__job_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnchorMode
         * @enum {string}
         */
        AnchorMode: "BACKTEST_START_PRICE" | "BACKTEST_AVG_PRICE" | "CURRENT_PRICE" | "CUSTOM_PRICE";
        /** BacktestAnchorPriceResponse */
        BacktestAnchorPriceResponse: {
            /** Anchor Price */
            anchor_price: number;
            /**
             * Anchor Time
             * Format: date-time
             */
            anchor_time: string;
            /**
             * Anchor Source
             * @enum {string}
             */
            anchor_source: "first_candle_close" | "avg_candle_close" | "last_candle_close" | "custom_price";
            /** Candle Count */
            candle_count: number;
        };
        /** BacktestJobMeta */
        BacktestJobMeta: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["BacktestJobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * BacktestJobStatus
         * @enum {string}
         */
        BacktestJobStatus: "pending" | "running" | "completed" | "failed" | "cancelled";
        /** BacktestRequest */
        "BacktestRequest-Input": {
            strategy: components["schemas"]["StrategyConfig"];
            data?: components["schemas"]["DataConfig"];
        };
        /** BacktestRequest */
        "BacktestRequest-Output": {
            strategy: components["schemas"]["StrategyConfig"];
            data?: components["schemas"]["DataConfig"];
        };
        /** BacktestResult */
        BacktestResult: {
            summary: components["schemas"]["BacktestSummary"];
            /** Candles */
            candles: components["schemas"]["Candle"][];
            /** Grid Lines */
            grid_lines: number[];
            /** Equity Curve */
            equity_curve: components["schemas"]["CurvePoint"][];
            /** Drawdown Curve */
            drawdown_curve: components["schemas"]["CurvePoint"][];
            /** Margin Ratio Curve */
            margin_ratio_curve: components["schemas"]["CurvePoint"][];
            /** Leverage Usage Curve */
            leverage_usage_curve: components["schemas"]["CurvePoint"][];
            /** Liquidation Price Curve */
            liquidation_price_curve: components["schemas"]["CurvePoint"][];
            /** Trades */
            trades: components["schemas"]["TradeEvent"][];
            /** Events */
            events: components["schemas"]["EventLog"][];
            analysis?: components["schemas"]["StrategyAnalysis"] | null;
            scoring?: components["schemas"]["StrategyScoring"] | null;
        };
        /** BacktestStartResponse */
        BacktestStartResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["BacktestJobStatus"];
            /**
             * Idempotency Reused
             * @default false
             */
            idempotency_reused: boolean;
        };
        /** BacktestStatusResponse */
        BacktestStatusResponse: {
            job: components["schemas"]["BacktestJobMeta"];
            result?: components["schemas"]["BacktestResult"] | null;
        };
        /** BacktestSummary */
        BacktestSummary: {
            /** Initial Margin */
            initial_margin: number;
            /** Final Equity */
            final_equity: number;
            /** Total Return Usdt */
            total_return_usdt: number;
            /** Total Return Pct */
            total_return_pct: number;
            /** Annualized Return Pct */
            annualized_return_pct: number | null;
            /** Average Round Profit */
            average_round_profit: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Max Single Loss */
            max_single_loss: number;
            /** Stop Loss Count */
            stop_loss_count: number;
            /** Liquidation Count */
            liquidation_count: number;
            /** Full Grid Profit Count */
            full_grid_profit_count: number;
            /** Win Rate */
            win_rate: number;
            /** Average Holding Hours */
            average_holding_hours: number;
            /** Total Closed Trades */
            total_closed_trades: number;
            /** Status */
            status: string;
            /** Fees Paid */
            fees_paid: number;
            /** Funding Paid */
            funding_paid: number;
            /** Use Base Position */
            use_base_position: boolean;
            /** Base Grid Count */
            base_grid_count: number;
            /** Initial Position Size */
            initial_position_size: number;
            /** Max Possible Loss Usdt */
            max_possible_loss_usdt: number;
        };
        /** Candle */
        Candle: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /**
             * Volume
             * @default 0
             */
            volume: number;
        };
        /** CurvePoint */
        CurvePoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
        };
        /** DataConfig */
        DataConfig: {
            /** @default binance */
            source: components["schemas"]["DataSource"];
            /**
             * Symbol
             * @default BTCUSDT
             */
            symbol: string;
            /** @default 1h */
            interval: components["schemas"]["Interval"];
            /**
             * Lookback Days
             * @default 14
             */
            lookback_days: number;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Csv Content */
            csv_content?: string | null;
        };
        /**
         * DataSource
         * @enum {string}
         */
        DataSource: "binance" | "bybit" | "okx" | "csv";
        /** EventLog */
        EventLog: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Event Type */
            event_type: string;
            /** Price */
            price: number;
            /** Message */
            message: string;
            /** Payload */
            payload?: Record<string, never> | null;
        };
        /**
         * GridSide
         * @enum {string}
         */
        GridSide: "long" | "short";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapCell */
        HeatmapCell: {
            /** Leverage */
            leverage: number;
            /** Grids */
            grids: number;
            /** Value */
            value: number;
            /** Use Base Position */
            use_base_position: boolean;
            /** Base Grid Count */
            base_grid_count: number;
            /** Initial Position Size */
            initial_position_size: number;
            /** Anchor Price */
            anchor_price: number;
            /** Lower Price */
            lower_price: number;
            /** Upper Price */
            upper_price: number;
            /** Stop Price */
            stop_price: number;
        };
        /**
         * Interval
         * @enum {string}
         */
        Interval: "1m" | "3m" | "5m" | "15m" | "30m" | "1h" | "2h" | "4h" | "6h" | "8h" | "12h" | "1d";
        /**
         * JobStreamType
         * @enum {string}
         */
        JobStreamType: "auto" | "backtest" | "optimization";
        /** MarketParamsResponse */
        MarketParamsResponse: {
            source: components["schemas"]["DataSource"];
            /** Symbol */
            symbol: string;
            /** Maker Fee Rate */
            maker_fee_rate: number;
            /** Taker Fee Rate */
            taker_fee_rate: number;
            /** Funding Rate Per 8H */
            funding_rate_per_8h: number;
            /** Funding Interval Hours */
            funding_interval_hours: number;
            /** Price Tick Size */
            price_tick_size: number;
            /** Quantity Step Size */
            quantity_step_size: number;
            /** Min Notional */
            min_notional: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Note */
            note?: string | null;
        };
        /** OptimizationConfig */
        OptimizationConfig: {
            /** @default random_pruned */
            optimization_mode: components["schemas"]["OptimizationMode"];
            /**
             * @default {
             *       "enabled": true,
             *       "start": 5,
             *       "end": 12,
             *       "step": 1
             *     }
             */
            leverage: components["schemas"]["SweepRange"];
            /**
             * @default {
             *       "enabled": true,
             *       "start": 4,
             *       "end": 12,
             *       "step": 1
             *     }
             */
            grids: components["schemas"]["SweepRange"];
            /**
             * @default {
             *       "enabled": true,
             *       "values": [
             *         5,
             *         8,
             *         10
             *       ]
             *     }
             */
            band_width_pct: components["schemas"]["SweepRange"];
            /**
             * @default {
             *       "enabled": true,
             *       "values": [
             *         0.5,
             *         1,
             *         2
             *       ]
             *     }
             */
            stop_loss_ratio_pct: components["schemas"]["SweepRange"];
            /**
             * Optimize Base Position
             * @default false
             */
            optimize_base_position: boolean;
            /** @default BACKTEST_START_PRICE */
            anchor_mode: components["schemas"]["AnchorMode"];
            /** Custom Anchor Price */
            custom_anchor_price?: number | null;
            /** @default return_drawdown_ratio */
            target: components["schemas"]["OptimizationTarget"];
            /** Custom Score Expr */
            custom_score_expr?: string | null;
            /**
             * Min Closed Trades
             * @default 0
             */
            min_closed_trades: number;
            /** Max Drawdown Pct Limit */
            max_drawdown_pct_limit?: number | null;
            /** Max Allowed Loss Usdt */
            max_allowed_loss_usdt?: number | null;
            /**
             * Require Positive Return
             * @default false
             */
            require_positive_return: boolean;
            /**
             * Robust Validation Weight
             * @default 0.7
             */
            robust_validation_weight: number;
            /**
             * Robust Gap Penalty
             * @default 0.2
             */
            robust_gap_penalty: number;
            /**
             * Max Combinations
             * @default 500
             */
            max_combinations: number;
            /**
             * Max Trials
             * @default 2000
             */
            max_trials: number;
            /**
             * Auto Limit Combinations
             * @default true
             */
            auto_limit_combinations: boolean;
            /** Max Workers */
            max_workers?: number;
            /**
             * Batch Size
             * @default 300
             */
            batch_size: number;
            /**
             * Chunk Size
             * @default 64
             */
            chunk_size: number;
            /**
             * Warmup Ratio
             * @default 0.15
             */
            warmup_ratio: number;
            /** Random Seed */
            random_seed?: number | null;
            /**
             * Resume Study
             * @default false
             */
            resume_study: boolean;
            /** Resume Study Key */
            resume_study_key?: string | null;
            /**
             * Bayesian Adaptive Fallback Enabled
             * @default true
             */
            bayesian_adaptive_fallback_enabled: boolean;
            /**
             * Bayesian Adaptive Slowdown Factor
             * @default 1.8
             */
            bayesian_adaptive_slowdown_factor: number;
            /**
             * Bayesian Adaptive Window Batches
             * @default 4
             */
            bayesian_adaptive_window_batches: number;
            /**
             * Bayesian Adaptive Min Trials After Warmup
             * @default 64
             */
            bayesian_adaptive_min_trials_after_warmup: number;
            /**
             * Enable Early Pruning
             * @default true
             */
            enable_early_pruning: boolean;
            /**
             * Drawdown Prune Multiplier
             * @default 1.5
             */
            drawdown_prune_multiplier: number;
            /**
             * Enable Profit Pruning
             * @default true
             */
            enable_profit_pruning: boolean;
            /**
             * Pruning Steps
             * @default 2
             */
            pruning_steps: number;
            /**
             * Enable Topk Refine
             * @default false
             */
            enable_topk_refine: boolean;
            /**
             * Topk Refine K
             * @default 5
             */
            topk_refine_k: number;
            /**
             * Refine Leverage Delta
             * @default 1
             */
            refine_leverage_delta: number;
            /**
             * Refine Grids Delta
             * @default 1
             */
            refine_grids_delta: number;
            /**
             * Refine Band Delta Pct
             * @default 0.5
             */
            refine_band_delta_pct: number;
            /**
             * Refine Stop Delta Pct
             * @default 0.25
             */
            refine_stop_delta_pct: number;
            /**
             * Walk Forward Enabled
             * @default true
             */
            walk_forward_enabled: boolean;
            /**
             * Train Ratio
             * @default 0.5
             */
            train_ratio: number;
        };
        /** OptimizationHeatmapResponse */
        OptimizationHeatmapResponse: {
            job: components["schemas"]["OptimizationJobMeta"];
            target: components["schemas"]["OptimizationTarget"];
            /**
             * Heatmap
             * @default []
             */
            heatmap: components["schemas"]["HeatmapCell"][];
            best_row?: components["schemas"]["OptimizationResultRow"] | null;
        };
        /** OptimizationHistoryPageResponse */
        OptimizationHistoryPageResponse: {
            /** Items */
            items: components["schemas"]["OptimizationProgressResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** OptimizationJobMeta */
        OptimizationJobMeta: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["OptimizationJobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Total Steps
             * @default 0
             */
            total_steps: number;
            /**
             * Completed Steps
             * @default 0
             */
            completed_steps: number;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Total Combinations
             * @default 0
             */
            total_combinations: number;
            /**
             * Trials Completed
             * @default 0
             */
            trials_completed: number;
            /**
             * Trials Pruned
             * @default 0
             */
            trials_pruned: number;
            /**
             * Pruning Ratio
             * @default 0
             */
            pruning_ratio: number;
        };
        /**
         * OptimizationJobStatus
         * @enum {string}
         */
        OptimizationJobStatus: "pending" | "running" | "completed" | "failed" | "cancelled";
        /**
         * OptimizationMode
         * @enum {string}
         */
        OptimizationMode: "grid" | "bayesian" | "random_pruned";
        /** OptimizationProgressPoint */
        OptimizationProgressPoint: {
            /** Step */
            step: number;
            /** Value */
            value: number;
        };
        /** OptimizationProgressResponse */
        OptimizationProgressResponse: {
            job: components["schemas"]["OptimizationJobMeta"];
            target: components["schemas"]["OptimizationTarget"];
        };
        /** OptimizationRequest */
        OptimizationRequest: {
            base_strategy: components["schemas"]["StrategyConfig"];
            data: components["schemas"]["DataConfig"];
            /**
             * @default {
             *       "optimization_mode": "random_pruned",
             *       "leverage": {
             *         "enabled": true,
             *         "end": 12,
             *         "start": 5,
             *         "step": 1
             *       },
             *       "grids": {
             *         "enabled": true,
             *         "end": 12,
             *         "start": 4,
             *         "step": 1
             *       },
             *       "band_width_pct": {
             *         "enabled": true,
             *         "values": [
             *           5,
             *           8,
             *           10
             *         ]
             *       },
             *       "stop_loss_ratio_pct": {
             *         "enabled": true,
             *         "values": [
             *           0.5,
             *           1,
             *           2
             *         ]
             *       },
             *       "optimize_base_position": false,
             *       "anchor_mode": "BACKTEST_START_PRICE",
             *       "target": "return_drawdown_ratio",
             *       "min_closed_trades": 0,
             *       "require_positive_return": false,
             *       "robust_validation_weight": 0.7,
             *       "robust_gap_penalty": 0.2,
             *       "max_combinations": 500,
             *       "max_trials": 2000,
             *       "auto_limit_combinations": true,
             *       "max_workers": 10,
             *       "batch_size": 300,
             *       "chunk_size": 64,
             *       "warmup_ratio": 0.15,
             *       "resume_study": false,
             *       "bayesian_adaptive_fallback_enabled": true,
             *       "bayesian_adaptive_slowdown_factor": 1.8,
             *       "bayesian_adaptive_window_batches": 4,
             *       "bayesian_adaptive_min_trials_after_warmup": 64,
             *       "enable_early_pruning": true,
             *       "drawdown_prune_multiplier": 1.5,
             *       "enable_profit_pruning": true,
             *       "pruning_steps": 2,
             *       "enable_topk_refine": false,
             *       "topk_refine_k": 5,
             *       "refine_leverage_delta": 1,
             *       "refine_grids_delta": 1,
             *       "refine_band_delta_pct": 0.5,
             *       "refine_stop_delta_pct": 0.25,
             *       "walk_forward_enabled": true,
             *       "train_ratio": 0.5
             *     }
             */
            optimization: components["schemas"]["OptimizationConfig"];
        };
        /** OptimizationResultRow */
        OptimizationResultRow: {
            /** Row Id */
            row_id: number;
            /** Leverage */
            leverage: number;
            /** Grids */
            grids: number;
            /** Use Base Position */
            use_base_position: boolean;
            /** Base Grid Count */
            base_grid_count: number;
            /** Initial Position Size */
            initial_position_size: number;
            /** Anchor Price */
            anchor_price: number;
            /** Lower Price */
            lower_price: number;
            /** Upper Price */
            upper_price: number;
            /** Stop Price */
            stop_price: number;
            /** Band Width Pct */
            band_width_pct: number;
            /** Range Lower */
            range_lower: number;
            /** Range Upper */
            range_upper: number;
            /** Stop Loss */
            stop_loss: number;
            /** Stop Loss Ratio Pct */
            stop_loss_ratio_pct: number;
            /**
             * Max Possible Loss Usdt
             * @default 0
             */
            max_possible_loss_usdt: number;
            /** Total Return Usdt */
            total_return_usdt: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Sharpe Ratio */
            sharpe_ratio: number;
            /** Win Rate */
            win_rate: number;
            /** Return Drawdown Ratio */
            return_drawdown_ratio: number;
            /** Score */
            score: number;
            /** Validation Total Return Usdt */
            validation_total_return_usdt?: number | null;
            /** Validation Max Drawdown Pct */
            validation_max_drawdown_pct?: number | null;
            /** Validation Sharpe Ratio */
            validation_sharpe_ratio?: number | null;
            /** Validation Win Rate */
            validation_win_rate?: number | null;
            /** Validation Return Drawdown Ratio */
            validation_return_drawdown_ratio?: number | null;
            /** Validation Score */
            validation_score?: number | null;
            /** Validation Total Closed Trades */
            validation_total_closed_trades?: number | null;
            /** Robust Score */
            robust_score?: number | null;
            /** Overfit Penalty */
            overfit_penalty?: number | null;
            /**
             * Passes Constraints
             * @default true
             */
            passes_constraints: boolean;
            /** Constraint Violations */
            constraint_violations?: string[];
            /** Total Closed Trades */
            total_closed_trades: number;
        };
        /** OptimizationRowsResponse */
        OptimizationRowsResponse: {
            job: components["schemas"]["OptimizationJobMeta"];
            target: components["schemas"]["OptimizationTarget"];
            /** Sort By */
            sort_by: string;
            sort_order: components["schemas"]["SortOrder"];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Results */
            total_results: number;
            /** Rows */
            rows: components["schemas"]["OptimizationResultRow"][];
            best_row?: components["schemas"]["OptimizationResultRow"] | null;
            best_validation_row?: components["schemas"]["OptimizationResultRow"] | null;
        };
        /** OptimizationStartResponse */
        OptimizationStartResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["OptimizationJobStatus"];
            /** Total Combinations */
            total_combinations: number;
            /**
             * Idempotency Reused
             * @default false
             */
            idempotency_reused: boolean;
        };
        /** OptimizationStatusResponse */
        OptimizationStatusResponse: {
            job: components["schemas"]["OptimizationJobMeta"];
            target: components["schemas"]["OptimizationTarget"];
            /** Sort By */
            sort_by: string;
            sort_order: components["schemas"]["SortOrder"];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Results */
            total_results: number;
            /** Rows */
            rows: components["schemas"]["OptimizationResultRow"][];
            best_row?: components["schemas"]["OptimizationResultRow"] | null;
            best_validation_row?: components["schemas"]["OptimizationResultRow"] | null;
            /**
             * Best Equity Curve
             * @default []
             */
            best_equity_curve: components["schemas"]["CurvePoint"][];
            /**
             * Best Score Progression
             * @default []
             */
            best_score_progression: components["schemas"]["OptimizationProgressPoint"][];
            /**
             * Convergence Curve Data
             * @default []
             */
            convergence_curve_data: components["schemas"]["OptimizationProgressPoint"][];
            /**
             * Heatmap
             * @default []
             */
            heatmap: components["schemas"]["HeatmapCell"][];
            train_window?: components["schemas"]["TimeWindowInfo"] | null;
            validation_window?: components["schemas"]["TimeWindowInfo"] | null;
        };
        /**
         * OptimizationTarget
         * @enum {string}
         */
        OptimizationTarget: "total_return" | "sharpe" | "min_drawdown" | "return_drawdown_ratio" | "custom";
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "desc" | "asc";
        /** StrategyAnalysis */
        StrategyAnalysis: {
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high";
            /**
             * Structure Dependency
             * @enum {string}
             */
            structure_dependency: "range" | "mixed" | "trend_sensitive";
            /** Overfitting Flag */
            overfitting_flag: boolean;
            /** Validation Degradation Pct */
            validation_degradation_pct: number;
            /**
             * Liquidation Risk
             * @enum {string}
             */
            liquidation_risk: "low" | "medium" | "high";
            /** Stability Score */
            stability_score: number;
            /** Diagnosis Tags */
            diagnosis_tags: string[];
            /** Ai Explanation */
            ai_explanation?: string | null;
        };
        /** StrategyConfig */
        StrategyConfig: {
            /** @default long */
            side: components["schemas"]["GridSide"];
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /** Grids */
            grids: number;
            /** Leverage */
            leverage: number;
            /** Margin */
            margin: number;
            /** Stop Loss */
            stop_loss: number;
            /**
             * Use Base Position
             * @default false
             */
            use_base_position: boolean;
            /**
             * Strict Risk Control
             * @default true
             */
            strict_risk_control: boolean;
            /**
             * Reopen After Stop
             * @default true
             */
            reopen_after_stop: boolean;
            /**
             * Fee Rate
             * @default 0.0004
             */
            fee_rate: number;
            /** Maker Fee Rate */
            maker_fee_rate?: number | null;
            /** Taker Fee Rate */
            taker_fee_rate?: number | null;
            /**
             * Slippage
             * @default 0
             */
            slippage: number;
            /**
             * Maintenance Margin Rate
             * @default 0.005
             */
            maintenance_margin_rate: number;
            /**
             * Funding Rate Per 8H
             * @default 0
             */
            funding_rate_per_8h: number;
            /**
             * Funding Interval Hours
             * @default 8
             */
            funding_interval_hours: number;
            /**
             * Use Mark Price For Liquidation
             * @default false
             */
            use_mark_price_for_liquidation: boolean;
            /**
             * Price Tick Size
             * @default 0
             */
            price_tick_size: number;
            /**
             * Quantity Step Size
             * @default 0
             */
            quantity_step_size: number;
            /**
             * Min Notional
             * @default 0
             */
            min_notional: number;
            /** Max Allowed Loss Usdt */
            max_allowed_loss_usdt?: number | null;
        };
        /** StrategyScoring */
        StrategyScoring: {
            /** Profit Score */
            profit_score: number;
            /** Risk Score */
            risk_score: number;
            /** Stability Score */
            stability_score: number;
            /** Robustness Score */
            robustness_score: number;
            /** Behavior Score */
            behavior_score: number;
            /** Final Score */
            final_score: number;
            /**
             * Grade
             * @enum {string}
             */
            grade: "A" | "B" | "C" | "D" | "E";
            /** Profit Reasons */
            profit_reasons?: string[];
            /** Risk Reasons */
            risk_reasons?: string[];
            /** Stability Reasons */
            stability_reasons?: string[];
            /** Robustness Reasons */
            robustness_reasons?: string[];
            /** Behavior Reasons */
            behavior_reasons?: string[];
        };
        /** SweepRange */
        SweepRange: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Start */
            start?: number | null;
            /** End */
            end?: number | null;
            /** Step */
            step?: number | null;
            /** Values */
            values?: number[] | null;
        };
        /** TimeWindowInfo */
        TimeWindowInfo: {
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Candles */
            candles: number;
        };
        /** TradeEvent */
        TradeEvent: {
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /**
             * Close Time
             * Format: date-time
             */
            close_time: string;
            /**
             * Side
             * @enum {string}
             */
            side: "long" | "short";
            /** Entry Price */
            entry_price: number;
            /** Exit Price */
            exit_price: number;
            /** Quantity */
            quantity: number;
            /** Gross Pnl */
            gross_pnl: number;
            /** Net Pnl */
            net_pnl: number;
            /** Fee Paid */
            fee_paid: number;
            /** Holding Hours */
            holding_hours: number;
            /**
             * Close Reason
             * @enum {string}
             */
            close_reason: "grid_take_profit" | "stop_loss" | "liquidation";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_api_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_defaults_api_v1_backtest_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRequest-Output"];
                };
            };
        };
    };
    run_backtest_api_api_v1_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_backtest_api_api_v1_backtest_start_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_anchor_price_api_api_v1_backtest_anchor_price_post: {
        parameters: {
            query?: {
                anchor_mode?: components["schemas"]["AnchorMode"];
                custom_anchor_price?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestAnchorPriceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_status_api_api_v1_backtest__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_api_api_v1_jobs__job_id__stream_get: {
        parameters: {
            query?: {
                job_type?: components["schemas"]["JobStreamType"];
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_cancel_api_api_v1_backtest__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_params_api_api_v1_market_params_get: {
        parameters: {
            query?: {
                source?: components["schemas"]["DataSource"];
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketParamsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_optimization_api_api_v1_optimization_start_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_status_api_api_v1_optimization__job_id__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort_by?: string;
                sort_order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_rows_api_api_v1_optimization__job_id__rows_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort_by?: string;
                sort_order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_heatmap_api_api_v1_optimization__job_id__heatmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationHeatmapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_progress_api_api_v1_optimization__job_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_history_api_api_v1_optimization_history_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: components["schemas"]["OptimizationJobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationHistoryPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_history_clear_api_api_v1_optimization_history_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Confirm-Action"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_history_selected_clear_api_api_v1_optimization_history_selected_delete: {
        parameters: {
            query: {
                job_id: string[];
            };
            header?: {
                "X-Confirm-Action"?: string | null;
                "X-Confirm-Count"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_history_selected_restore_api_api_v1_optimization_history_restore_selected_post: {
        parameters: {
            query: {
                job_id: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_cancel_api_api_v1_optimization__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_restart_api_api_v1_optimization__job_id__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_export_api_api_v1_optimization__job_id__export_get: {
        parameters: {
            query?: {
                sort_by?: string;
                sort_order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
